--liquibase formatted sql
--changeset antoxakon:2  -- Формат: author:id
--comment: create table owners

create table if not exists owners
(
    id  bigint generated by default as identity primary key,
    animal_owner_uuid uuid         not null unique,
    first_name        varchar(255) not null,
    last_name         varchar(255) not null unique
);