--liquibase formatted sql
--changeset antoxakon:3  -- Формат: author:id
--comment: create table animals

create table if not exists animals
(
    id  bigint generated by default as identity primary key,
    animal_id   uuid         not null unique,
    animal_name varchar(255) not null,
    animal_type varchar(255) not null,
    owner_id    bigint       not null references owners(id)
);